name: H3K4me3
environment:
    image:
        gpu: docker.io/junhongshen/nb360:updatenew
hyperparameters:
    dataset: H3K4me3 #DEEPSEA
    embedder_dataset: text
    objective: MMD
    weight: roberta
    maxsamples: 256 #512
    target_seq_len: 128 #256 #512

    experiment_id: 14 

    seed: 0
    epochs: 30 #25
    embedder_epochs: 100 
    pretrain_epochs: 0 
    predictor_epochs: 0 

    joint_optim: True
    alpha: 0.01 # weight for otdd 
    beta: 1 # weight for bce
    finetune_method: all
    one_hot: True

    lora_r: 12 # 12
    lora_alpha: 32 # 32
    lora_dropout: 0.1
    lora_target_modules: ["q_proj", "v_proj"]

    drop_out: 0.05
    label_smoothing_factor: 0
    activation: None
    rc_aug: True # reverse complement augmentation
    shift_aug: True # shift augmentation

    use_wandb: True
    wandb_key: "ef4b923327eb2a110fda334efee4ec80feee4bc7"
    data_parallel: False
    quantize: False

    embedder_type: "resnet" # dash, unet,dash random
    embedder_init: "pretrained"
    ks: [3, 5, 3, 3, 3, 5, 5, 7, 5] 
    ds: [1, 1, 1, 1, 5, 1, 1, 1, 1]
    emedder_path: "/home/wenduoc/DASH/src/results_acc/H3K4me3/wrn/wrn/1/network_weights.pt"


    batch_size: 64 #128 
    eval_batch_size: 1000
    accum: 1
    clip: 1 
    validation_freq: 1

    optimizer:
        name: Adam
        params:
            lr: 0.00005 # 0.000005
            betas: [0.9, 0.98] 
            weight_decay: 0.00001
            momentum: 0.99
    
    embedder_optimizer:
        name: SGD
        params:
            lr: 0.01 # 0.000005
            betas: [0.9, 0.98] 
            weight_decay: 0.000005
            momentum: 0.99
    
    scheduler:  
        name: WarmupLR
        params:
            warmup_epochs: 5
            decay_epochs: 30
            sched: [30, 60, 90]
            base: 0.2

    no_warmup_scheduler:  
        name: StepLR
        params:
            warmup_epochs: 10
            decay_epochs: 100
            sched: [40, 60, 80]
            base: 0.2

    num_workers: 2
    reproducibility: False
    valid_split: False

min_validation_period:
    epochs: 1
bind_mounts:
    - host_path: /tmp
      container_path: /data
    - host_path: /tmp
      container_path: /root/.cache
resources:
  slots_per_trial: 1
records_per_epoch: 9281
searcher:
  name:  single
  metric: accuracy
  smaller_is_better: false
  max_length:
    epochs: 1
max_restarts: 0
entrypoint: python3 -W ignore main.py
